<?

// file generated by plugin translationbrowser, Author: Mariusz Bulkowski 

$french = array( 
   'friends:invite'  =>  "Inviter des amis!" , 
   'invitefriends:introduction'  =>  "Pour inviter des amis à rejoindre ce réseau, merci d'entrer leurs emails ci-dessous (un mail par ligne):" , 
   'invitefriends:message'  =>  "Merci d'ajouter un message accompagnant votre invitation" , 
   'invitefriends:subject'  =>  "Invitation pour rejoindre %s" , 
   'invitefriends:success'  =>  "Vos amis ont été invités." , 
   'invitefriends:failure'  =>  "Vos amis n'ont pas pu être invités." , 
   'invitefriends:message:default'  =>  "Salut,

Je t'invite à me rejoindre sur %s." , 
   'invitefriends:email'  =>  "Vous avez été invité à rejoindre %s par %s. Voici un message de sa part:"
);


add_translation("fr",$french);



?>