<?

// file generated by plugin translationbrowser, Author: Mariusz Bulkowski 

$french = array( 
   'tagcloud:widget:title'  =>  "Nuage de mots clés" , 
   'tagcloud:widget:description'  =>  "Nuage de mots clés" , 
   'tagcloud:widget:notags'  =>  "Nombre de tags à afficher"
);


add_translation("fr",$french);



?>