<?

// file generated by plugin translationbrowser, Author: Mariusz Bulkowski 

$french = array( 
   'status'  =>  "Status" , 
   'status:user'  =>  "Le statut de %s" , 
   'status:current'  =>  "Mon statut actuel" , 
   'status:desc'  =>  "Ce widget affiche votre statut" , 
   'status:posttitle'  =>  "Le statut de %s: %s" , 
   'status:everyone'  =>  "Tous les statuts" , 
   'status:strapline'  =>  "%s" , 
   'status:addstatus'  =>  "Changer votre statut" , 
   'status:messages'  =>  "Les messages de statut" , 
   'status:text'  =>  "Statut:" , 
   'status:set'  =>  "changé " , 
   'status:clear'  =>  "Remettre à zero son statut" , 
   'status:delete'  =>  "supprimer son statut" , 
   'status:nostatus'  =>  "Aucun statut." , 
   'status:viewhistory'  =>  "Voir tous les statuts" , 
   'item:object:status'  =>  "Les messages de statut" , 
   'status:river:created'  =>  "%s a mis à jour" , 
   'status:river:create'  =>  "son statut." , 
   'status:posted'  =>  "Votre nouveau statut a bien été mis à jour." , 
   'status:deleted'  =>  "Votre nouveau statut a bien été supprimé." , 
   'status:blank'  =>  "Désolé : vous devez écrire quelque chose avant de pouvoir soumettre votre statut." , 
   'status:notfound'  =>  "Désolé, nous ne pouvons pas trouver le statut recherché." , 
   'status:notdeleted'  =>  "Désolé, nous ne pouvons pas supprimer votre statut." , 
   'status:notsaved'  =>  "Un problème est survenu. Merci d'essayer de nouveau. Si le problème persiste, merci de contacter l'administrateur." , 
   'status:problem'  =>  "Un problème est survenu. Vous ne pouvez pas éditer votre statut."
);


add_translation("fr",$french);



?>