<?

// file generated by plugin translationbrowser, Author: Mariusz Bulkowski 

$french = array( 
   'friendrequest'  =>  "Demande d'amitié" , 
   'friendrequests'  =>  "Demandes d'amitié" , 
   'friendrequests:title'  =>  "Les demandes d'amitié de %s" , 
   'newfriendrequests'  =>  "De nouvelles demandes d'amitié!" , 
   'friendrequest:add:exists'  =>  "Vous avez déjà demandé à être amis avec %s." , 
   'friendrequest:add:failure'  =>  "Désolé, une erreur est survenue. Merci de retenter." , 
   'friendrequest:add:successful'  =>  "Vous avez demandé à être ami avec %s. La demande doit être approuvée." , 
   'friendrequest:newfriend:subject'  =>  "%s veut être votre ami!" , 
   'friendrequest:newfriend:body'  =>  "%s veut être votre ami! Mais il attend votre réponse... Connectez vous pour finaliser la demande!

Vous pouvez voir les demandes en attente ici:

	%s

(Ne répondez pas à cet email..)" , 
   'friendrequest:successful'  =>  "Vous êtes maintenant ami avec %s!" , 
   'friendrequest:remove:success'  =>  "La demande a bien été enlevée." , 
   'friendrequest:remove:fail'  =>  "Impossible de supprimer la demande." , 
   'friendrequest:approvefail'  =>  "Erreur inconnue pendant l'ajout de %s comme ami!"
);


add_translation("fr",$french);



?>